services:
  dev:
    container_name: app
    image: app:dev
    build: .
    command: npm run start-dev
    ports:
    - 3000:3000
    volumes:
    - .:/src
    env_file:
    - .env

  unit-test:
    container_name: unit-test
    image: unit-test:latest
    build: ./
    command: npm run unit-test

  integration-test:
    container_name: integration-test
    image: integration-test:latest
    build: ./
    network_mode: host
    command: npm run integration-test
  