services:
  app:
    container_name: app
    image: app:dev
    build: .
    command: npm run start-dev
    ports:
    - 3000:3000
    volumes:
    - .:/src
    env_file:
    - .env

  test:
    container_name: test
    image: test:latest
    build: ./
    command: >
      sh -c "pwd &&
             npm install &&
             npm run test"
    env_file:
    - .env