services:
    test:
      container_name: test
      image: test:latest
      build: ./
      command: npm run test
      environment:
        - DB_CONNECTOR=${{ secrets.DB_CONNECTOR }}
        - TOKEN_SECRET=${{ secrets.TOKEN_SECRET }}