name: build-and-test
on:
    pull_request:
        branches: [dev]

env:
  DB_CONNECTOR: ${{ secrets.DB_CONNECTOR }}
  TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: 'Create env file'
              run: |
                touch .env
                echo "DB_CONNECTOR=${{ secrets.DB_CONNECTOR }}" >> .env
                echo "TOKEN_SECRET=${{ secrets.TOKEN_SECRET }}" >> .env
                cat .env
            - name: build & run test
              run: docker compose up --exit-code-from test