name: build-and-test
on:
    pull_request:
        branches: [dev]

env:
  DB_CONNECTOR: ${{ secrets.DB_CONNECTOR }}
  TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: build & run test
              run: docker compose up test-github