name: integration-test
on:
    push:
        branches: [dev]

env:
  DB_CONNECTOR: ${{ secrets.DB_CONNECTOR }}
  TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: 'Create env file'
              run: |
                touch .env
                echo "DB_CONNECTOR=${{ secrets.DB_CONNECTOR }}" >> .env
                echo "TOKEN_SECRET=${{ secrets.TOKEN_SECRET }}" >> .env
            - name: build image
              run: docker image build -t app:latest .
            - name: build container
              run: docker container run -d --name app --publish 3000:3000 app:latest
            - name: wait a bit
              run: sleep 1
            - name: run integration test
              run: docker compose up integration-test --exit-code-from integration-test